### ISSUE TITLE
BOM Request

### ISSUE THREAD

**Issue by ptdecker** [svenpetersen1965/C64-A-V-Adaptor#1]
Hello!

I had a set of six of your boards made.  I'm now trying to locate the parts.  Could you recommend a part number and supplier for your RCA jacks and the S-Video plug?  All the RCA jacks I am finding do not have the pin arrangements (four in a square plus one center).  Also, I have tried Allied but have not had any luck finding a PCB mount for the 8-pin DIN.  Specific part numbers would be awesome for it as well.

(BTW, the boards are well done!  Nice work!)

P. Todd

**Comment by svenpetersen1965** [comment]
Did you check the BOM? [https://github.com/svenpetersen1965/C64-A-V-Adaptor/tree/master/Rev.%201/Excel](url)
There are the specific manufacturers, part numbers and some sources included.

**Comment by ptdecker** [comment]
My apology.  I did not see these the first time.

**Comment by svenpetersen1965** [comment]
No problem :-)
