### ISSUE TITLE
Lumberg BTOR 1 connectors are discontinued

### ISSUE THREAD

**Issue by tyristori** [svenpetersen1965/C64-A-V-Adaptor#2]
Lumberg has discontinued the RCA connectors used in the adaptor.

Alternatives could be Keystone 577, 584, 585 and 586 but the footprint is different.

[584_586-744919.pdf](https://github.com/svenpetersen1965/C64-A-V-Adaptor/files/8999694/584_586-744919.pdf)

**Comment by svenpetersen1965** [comment]
I am aware of the BTOR1 being discontinued. I have already made a new board with this footprint: [https://cdn.fbsbx.com/v/t59.2708-21/283406330_1343687749374559_2201800946223997816_n.pdf/rcj-02x.pdf?_nc_cat=104&ccb=1-7&_nc_sid=0cab14&_nc_ohc=YmccTe1ed_oAX-kSjtH&_nc_ht=cdn.fbsbx.com&oh=03_AVJN2fEY0uwKx9KMJgDpHFdPscT_h2HxKxKDZvWZTzWxKw&oe=62BC5327&dl=1](url). It seems to be compatible with the connector, that you have sent me. The PCBs are already ordered. 
-cu
Sven
