### ISSUE TITLE
Audio In needs attenuation

### ISSUE THREAD

**Issue by gsteemso** [svenpetersen1965/C64-A-V-Adaptor#3]
As I understand it, a standard audio "line in" level has s maximum of 0.7 V.  However, per the data sheet, a SID chip accepts a maximum of 0.6 V.  (I'm not sure if these are peak-to-peak or peak-to-ground measurements.)  The only reason I have never dared to use my Commodore's audio input line - which I would very much like to try, as SIDs were designed to be daisy-chainable - is because of this issue.  If doing so fries my SID, there are no more _real_ ones to replace it with, only reimplementations of varying accuracy.

**Comment by svenpetersen1965** [comment]
Hi, 
Please excuse my delayed reply. I wasn’t feeling so well.

Maybe, we have different data sheets. The one I have specifies the voltage on the Pin ExtIn (Pin 26) as follows:
„Any voltage applied directly to the pin should ride at dc level of 6 volts and should not exceed 3 volt p-p“

That is on page 8 of the data sheet. Unfortunately, it is neither marked with a date nor a version.  

The audio in pin on the A/V jack is ac coupled with a 100nF cap. The data sheet actually requests a capacitor of 1 to 10μF. So right now, I don’t see a problem here.

Regards,
Sven

**Comment by gsteemso** [comment]
After some digging, it looks like thd one I saw was a preliminary version.  It containing a figure that was off by one decimal position makes sense.  A great relief!

Marking this closed.
